# Generated by Django 5.0.2 on 2025-10-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_new', '0003_auto_20250821_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincommand',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admincommand',
            name='command_type',
            field=models.CharField(choices=[('approve_payment', 'Approve Payment'), ('reject_payment', 'Reject Payment'), ('approve_kyc', 'Approve KYC'), ('reject_kyc', 'Reject KYC'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('promote_user', 'Promote User'), ('demote_user', 'Demote User'), ('system_status', 'System Status'), ('user_stats', 'User Stats'), ('payment_stats', 'Payment Stats'), ('create_promo', 'Create Promo Code'), ('list_promos', 'List Promo Codes'), ('promo_stats', 'Promo Statistics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admincommand',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='Telegram User ID', unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('main_admin', 'Главный Администратор'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Пользователь')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_users', to='telegram_bot_new.botuser')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='admincommand',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot_new.botuser'),
        ),
    ]
