# Generated by Django 5.0.2 on 2025-10-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_new', '0004_admincommand_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='Link to main User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
