# Generated by Django 5.0.2 on 2025-10-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_new', '0005_botuser_linked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('q1_source', models.TextField(help_text='Откуда про нас узнали?')),
                ('q2_experience', models.TextField(help_text='Как давно занимаетесь трафиком?')),
                ('q3_ubt_knowledge', models.TextField(help_text='Что знаете про УБТ?')),
                ('q4_projects', models.TextField(help_text='На какие проекты проливали?')),
                ('q5_hours', models.TextField(help_text='Сколько часов в неделю готовы работать?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='telegram_bot_new.botuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='telegram_bot_new.botuser')),
            ],
            options={
                'verbose_name': 'Manager Application',
                'verbose_name_plural': 'Manager Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
